name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: check code style
        run: chmod +x ./gradlew --continue ktlintCheck
      - name: build for debug
        if:
        run: chmod +x ./gradlew assembleDebug appDistributionUploadDebug
